Terminado: Building Block View
Arquisoft/dede_es5a pull request #102
Opened 2022-03-17 18:57 UTC by uo276406

he terminado el punto 5 de la documentación.... Creo que está más o menos bien (al menos lo que es de restapi). Puede estar algo flojo lo de webapp, que me falte alguna cosa o lo que sea, analizad detenidamente lo que es de webapp :)) . En cualquier caso decidme cualquier cosa que veais mal. Seguro que hay faltas de ortografía... Y muchas otras cosas mal seguro :rofl:

2022-03-17 19:04 UTC, uo276406 commented
Os voy a dejar el index.html generado que seguro que es más fácil de corregir que desde aqui!!! :D
[index.html.gz](https://github.com/Arquisoft/dede_es5a/files/8289418/index.html.gz)
Pd.: Perdón por el formato... Creo que puede verse.

2022-03-23 20:13 UTC, uo276406 commented
@SofiaYYQ @UO250825 @mariaurrutia97 @AlonsoA-hub  ya he corregido el error del building block view que hablamos en la reunión y he añadido nuevos términos al glosario... Creo que no falta nada :smile:

2022-03-24 00:59 UTC, SofiaYYQ commented
Holaa, lo veo bien

2022-03-24 01:08 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +Building block view shows the static decomposition of the system into building blocks, it includes libraries, modules, components... An also the dependencies among them.
"And" en vez de "An"

2022-03-24 01:25 UTC, SofiaYYQ requested changes

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +This diagram shows the relations of the application among many others systems. It also shws dependency relations with clients. This diagram provides readers a general static vision of the project.
"shows" en vez de "shws"

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _Solid infrestructure_ | Mechanism to store data taking care of privacy. Packages (npm): _still to decide_.
"infrastructure" en vez de "infrestructure"

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _Server_ | this element has the responsability of manage requests of application's clients. These requests come from the webapp.
"responsibility" en vez de "responsability"

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _Models_ | Stores classes which represent objects form databse. Packages (npm): mongodb.
from en vez de form
database en vez de databse

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +| link:https://www.tawdis.net/[tawdis.net] | Webapge that allow as to check webpage accesibility using level AA
Webpage en vez de Webapge

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +| link:https://www.tawdis.net/[tawdis.net] | Webapge that allow as to check webpage accesibility using level AA
accessibility en vez de accesibility

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +| mongodb | Official mongodb driver for Node.js. Usage docuemntation can be found in this link:https://www.npmjs.com/package/mongodb[webapge].
documentation en vez de docuemntation
webpage en vez de webapge

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +|Picker express API| Api which helps to calculate orders' price and many other things related to order's management. Here is the link:https://www.pickerexpress.com/[docuementation].
documentation en vez de docuementation

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +|MongoDB Atlas| Service suported by mongoDB which allows the application to externalize the data storage. data is stored using serverless architecture managed by mongoDB with AWS, Azure or Google Clo
supported en vez de suported
data empieza por mayúscula

2022-03-24 01:25 UTC, SofiaYYQ commented on docs/12_glossary.adoc
> +| dotenv | Library from npm used to get environment variables that should not be xpesoed to the public. API keys, passwords, database links, ports... In this way .env files should not be in the repos
exposed en vez de xpesoed, me imagino 😅

2022-03-24 08:07 UTC, uo276406 commented
@SofiaYYQ muchas gracias, lo siento mucho por las erratas...

2022-03-24 08:57 UTC, SofiaYYQ approved these changes

2022-03-24 10:11 UTC, merged