Requirements overview: Diagrama casos de uso
Arquisoft/dede_es5a pull request #124
Opened 2022-04-01 18:40 UTC by uo276406

Terminado el diagrama de casos de uso

2022-04-01 18:41 UTC, uo276406 commented
Lo dejo con un deploy en la documentación del proyecto para que lo veais... Cree una nueva rama solo para esto, porque la de Diego mia tiene mucha basura por el tema del despliegue y modifique muchas cosas que no quiero subir :))

2022-04-01 20:28 UTC, SofiaYYQ requested changes
Y creo que faltaría ver productos

2022-04-01 20:28 UTC, SofiaYYQ commented on docs/01_introduction_and_goals.adoc
> +package Arquisocks {
ArquiSocks con s en mayúscula

2022-04-01 20:28 UTC, SofiaYYQ commented on docs/01_introduction_and_goals.adoc
> +  usecase "Create order" as co
En vez de "create order", yo creo que es mejor "place order", porque no sé, como que el cliente no lo crea.

2022-04-01 22:56 UTC, uo276406 commented
> Y creo que faltaría ver productos

Okey, lo corrijo mañana las mejoras y añado lo que falta :). Muchas gracias!!

2022-04-02 08:46 UTC, uo276406 commented on docs/01_introduction_and_goals.adoc
> +  usecase "Create order" as co
Ya está puesto PlaceOrder

2022-04-02 09:59 UTC, SofiaYYQ approved these changes
Yo lo veo bien 👍 , no se me ocurre nada más que añadir

2022-04-02 10:02 UTC, uo276406 commented
> Yo lo veo bien 👍 , no se me ocurre nada más que añadir

Creo que tengo añadir una flecah de solid pod a place order ¿comó lo ves?
Lo digo por el tema de coger la dirección

2022-04-02 10:08 UTC, SofiaYYQ commented
> > Yo lo veo bien 👍 , no se me ocurre nada más que añadir
> 
> Creo que tengo añadir una flecha de solid pod a place order ¿comó lo ves? Lo digo por el tema de coger la dirección

Ay, sí, lo veo bien 👍

2022-04-02 10:10 UTC, merged