Corregido punto 5: Building Block View
Arquisoft/dede_es5a pull request #161
Opened 2022-04-13 10:12 UTC by uo276406

Lo cambie un poco eliminando el nivel que nos dijo que había que poner librerías. A ver como lo veis... Cualquier fallo o aspecto a mejorar decidme... En cualquier caso si no el jueves le preguntamos a ver cómo lo ve la profe.

2022-04-15 14:44 UTC, SofiaYYQ requested changes
¿Será mejor que lo modifique yo haciendo un commit? Es por la parte de webapp que ahora tengo más idea sobre la webapp 😅.

2022-04-15 14:44 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _Components_ | Contains all of the components of the webapp, from the cart to the products list. Packages (npm): mui, inrupt/solid-ui-react.
En Components pondría mejor "Contains all ui components of the webapp, like cart, order, navbar, footer... Packages (npm): mui, inrupt/solid-ui-react."

2022-04-15 14:44 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _App_ | The main page of the web. Packages (npm): mui.
Busqué ahora por internet sobre qué es App.js, y es "main component in React which acts as a container for all other components". 
Pondría entonces algo como "Main component which contains all other components. Packages (npm): mui."

2022-04-15 14:44 UTC, SofiaYYQ commented on docs/05_building_block_view.adoc
> +| _Contexts_ | It is like the session of the user, it stores products selected.
![image](https://user-images.githubusercontent.com/79652551/163583618-5baf1636-34c1-4b0d-afe4-27429ec53603.png)
Entonces pondría mejor "allows to share data across the components more easily. For now, the context is sharing selected products in cart".

2022-04-15 14:49 UTC, SofiaYYQ commented
Por cierto, creo que aquí es al revés, porque la app está formada por componente 🤔 
![image](https://user-images.githubusercontent.com/79652551/163585075-a7b487f2-e3bf-4f6e-9ab1-0bd78a7711a0.png)

2022-04-15 14:52 UTC, uo276406 commented
> ¿Será mejor que lo modifique yo haciendo un commit? Es por la parte de webapp que ahora tengo más idea sobre la webapp 😅.

Mmmm como quieras, lo de webapp si que está flojo, así que seguro que lo haces mejor que yo :))... si quieres continuarlo tu sin problema vaya

2022-04-15 14:56 UTC, uo276406 commented
Ahora no estoy en casa :((... @SofiaYYQ si no puedes corregirlo, lo corrijo yo mañana sin falta. Me dices. Una cosa, lo de quitar un nivel lo ves bien? En plan lo de meter restapi y webapp dentro de arquisocks en el primer nivel? 🤔

2022-04-15 17:49 UTC, SofiaYYQ commented
> Ahora no estoy en casa :((... @SofiaYYQ si no puedes corregirlo, lo corrijo yo mañana sin falta. Me dices. Una cosa, lo de quitar un nivel lo ves bien? En plan lo de meter restapi y webapp dentro de arquisocks en el primer nivel? 🤔

Como quieras, pero hoy no voy a poder corregirlo. Tengo q acabar lo de ASR😢 

Y sí, lo veo bien 👍 , porque más librerías tampoco se me ocurre poner. Además las librerías de webapp y restapi ya lo tenemos en sus correspondientes apartados.

2022-04-16 08:16 UTC, uo276406 commented
> Por cierto, creo que aquí es al revés, porque la app está formada por componentes 🤔 ![image](https://user-images.githubusercontent.com/79652551/163585075-a7b487f2-e3bf-4f6e-9ab1-0bd78a7711a0.png)

mmmm... Creo que si está formada de componentes es como está @SofiaYYQ, por qué eso indica como que la app no puede funcionar sin los componentes. Quiero decir, la app como que deja el hueco y lo rellenan los componentes. Me dices pero el resto de cosas las pensé así vaya 😅

2022-04-16 10:32 UTC, SofiaYYQ commented
> > Por cierto, creo que aquí es al revés, porque la app está formada por componentes 🤔 ![image](https://user-images.githubusercontent.com/79652551/163585075-a7b487f2-e3bf-4f6e-9ab1-0bd78a7711a0.png)
> 
> mmmm... Creo que si está formada de componentes es como está @SofiaYYQ, por qué eso indica como que la app no puede funcionar sin los componentes. Quiero decir, la app como que deja el hueco y lo rellenan los componentes. Me dices pero el resto de cosas las pensé así vaya 😅

@uo276406, tienes razón, me líe, porque leí la relación según la dirección que aparece en la leyenda😅. Será mejor que lo pusiéramos al revés? Me refiero a esto:
![image](https://user-images.githubusercontent.com/79652551/163671500-e4ed15f0-be49-405c-a367-bbde3ca3d886.png)

2022-04-16 10:34 UTC, uo276406 commented
> > > Por cierto, creo que aquí es al revés, porque la app está formada por componentes 🤔 ![image](https://user-images.githubusercontent.com/79652551/163585075-a7b487f2-e3bf-4f6e-9ab1-0bd78a7711a0.png)
> > 
> > 
> > mmmm... Creo que si está formada de componentes es como está @SofiaYYQ, por qué eso indica como que la app no puede funcionar sin los componentes. Quiero decir, la app como que deja el hueco y lo rellenan los componentes. Me dices pero el resto de cosas las pensé así vaya 😅
> 
> @uo276406, tienes razón, me líe, porque leí la relación según la dirección que aparece en la leyenda😅. Será mejor que lo pusiéramos al revés? Me refiero a esto: ![image](https://user-images.githubusercontent.com/79652551/163671500-e4ed15f0-be49-405c-a367-bbde3ca3d886.png)

Okey, la leyenda sí, quizá sea mejor. Lo cambio ahora!! 😄

2022-04-16 10:37 UTC, SofiaYYQ approved these changes

2022-04-16 10:41 UTC, uo276406 commented
Okey, @SofiaYYQ hago squash entonces !!! Gracias por revisarlo 😅

2022-04-16 10:42 UTC, merged

2022-04-16 10:47 UTC, SofiaYYQ commented
> Okey, @SofiaYYQ hago squash entonces !!! Gracias por revisarlo 😅

Gracias a ti tb por revisar lo mío, también hice un squash por demasiados commits 😅 . 

Y al hacer merge del pull request no cierran los issues creo q es porque el merge tiene q hacerlo a la rama master :(
https://stackoverflow.com/questions/28771868/github-pull-request-close-issue-does-not-work